# ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã®è¡¨ç¤ºé †åº
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
[â”‚](bold green) $directory$git_branch$git_metrics$git_status$python$memory_usage$cmd_duration
[â””â”€>](bold green) $character"""

# å…¥åŠ›è¡Œã®ã‚¢ã‚¤ã‚³ãƒ³
[character]
success_symbol = "[âš¡](bold green)"
error_symbol = "[âœ–](bold red)"

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒª (ãƒ‘ã‚¹)
[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bold cyan"

# Gité–¢é€£
[git_branch]
symbol = "ï˜ "
style = "bold purple"

[git_status]
style = "bold red"
format = '[$all_status$ahead_behind]($style) '

[git_metrics]
disabled = false
added_style = "bold blue"
deleted_style = "bold red"

# Pythonç’°å¢ƒ
[python]
symbol = "ğŸ"
style = "bold yellow"
format = '[${symbol}${version} (\($virtualenv\))]($style) '

# ãƒ¡ãƒ¢ãƒª (è§£æç”¨)
[memory_usage]
disabled = false
threshold = 80
symbol = "ğŸ”¥"
format = '$symbol[${ram_pct}%]($style) '
style = "bold red"

# ã‚³ãƒãƒ³ãƒ‰å®Ÿè¡Œæ™‚é–“
[cmd_duration]
min_time = 2000
format = "â± [$duration]($style) "
style = "bold yellow"