# ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã§ã¯ã™ã¹ã¦ã®ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ãŒè¡¨ç¤ºã•ã‚Œã¾ã™ãŒã€
# ã“ã“ã§æ˜ç¤ºçš„ã«è¨˜è¿°ã™ã‚‹ã¨ã€æ›¸ã‹ã‚ŒãŸã‚‚ã®ã ã‘ãŒè¡¨ç¤ºã•ã‚Œã¾ã™ã€‚
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""
right_format = """$time"""
# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®å‰ã«ç©ºè¡Œã‚’å…¥ã‚Œã‚‹ã‹ (falseã§è©°ã‚è¾¼ã‚€)
add_newline = true 

# ã‚³ãƒãƒ³ãƒ‰ã®å®Ÿè¡Œæ™‚é–“ãŒã“ã®ãƒŸãƒªç§’ã‚’è¶…ãˆãŸã‚‰æ™‚é–“ã‚’è¡¨ç¤º
command_timeout = 500

[directory]
truncation_length = 3      # æ·±ã•ãŒ3éšå±¤ã‚’è¶…ãˆãŸã‚‰çŸ­ç¸®ã™ã‚‹
truncation_symbol = "â€¦/"   # çŸ­ç¸®æ™‚ã®è¨˜å·
style = "bold cyan"        # è‰²ã®è¨­å®š
read_only = " ğŸ”’"          # èª­ã¿å–ã‚Šå°‚ç”¨æ™‚ã®è¨˜å·

[git_branch]
symbol = "ğŸŒ± "
style = "bold green"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
modified = "ğŸ“"

[character]
success_symbol = "[âœ](bold green)"      # æˆåŠŸæ™‚
error_symbol = "[âœ—](bold red)"          # ã‚¨ãƒ©ãƒ¼æ™‚
vimcmd_symbol = "[V](bold green)"       # Vimãƒ¢ãƒ¼ãƒ‰(Normal)æ™‚

[python]
format = "via [Python3: $version]"